module: AmplifyMapLibre
author: Amazon Web Services
github_url: https://github.com/aws-amplify/amplify-ios-maplibre

clean: true
skip_undocumented: false
undocumented_text: ""
hide_documentation_coverage: true
sdk: iphone
theme: apple
