# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
    xcodebuild_and_test:
        macos:
            xcode: 13.4
        steps:
            - checkout
            - run:
                name: Build and test
                command: xcodebuild test -scheme "AmplifyMapLibreAdapter-Package" -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --simple --color --report junit


    host_app_ui_testing:
        working_directory: ~/amplify-ios-maplibre/HostApp
        macos:
            xcode: 13.4
        steps:
            - checkout
            - run:
                name: UI Test HostApp
                command: xcodebuild test -scheme HostApp -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --simple --color --report junit



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    build_test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
        jobs:
        - xcodebuild_and_test   
