name: Unit Test | AmplifyMapLibreAdaptor
on:
  workflow_dispatch:
  push:

permissions:
    contents: read

jobs:
  xcodebuild_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Build and test
        run: xcodebuild test -scheme "AmplifyMapLibreAdapter-Package" -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}
